use_frameworks!

target 'UICollectionViewCellAutomaticDimension_Example' do
  pod 'UICollectionViewCellAutomaticDimension', :path => '../'

  target 'UICollectionViewCellAutomaticDimension_Tests' do
    inherit! :search_paths

    
  end
end
